\context ChordNames	\chords {
	% intro
	a2:m a2:m7/g f2 e2 e2

	% estrofa 1
	a2:m g2 f2 g2
	a2:m g2 f2 g2
	c2 g2 f2 g2
	c2 g2 f2 g2 g2

	% estrofa 2
	a2:m g2 f2 g2
	c2 g2 f2 g2 g2

	c2 f2 g2 e2
	a4:m a4:m7/g f4 f4:maj7/e g2 g2
	c2 f2 g2 e2
	a4:m a4:m7/g f4 f4:maj7/e g2 g2

	% interludio
	f2 g2 a2:m f2
	g2 e2 a2:m e2

	% estrofa
	a2:m g2 f2 g2
	a2:m g2 f2 g2
	c2 g2 f2 g2
	c2 g2 f2 g2 g2

	c2 f2 g2 e2
	a4:m a4:m7/g f4 f4:maj7/e g2 g2
	c2 f2 g2 e2
	a4:m a4:m7/g f4 f4:maj7/e g2 g2

	c2 f2 g2 e2
	a4:m a4:m7/g f4 f4:maj7/e g2 g2

	d2 g2 a2 fis2 b4:m b4:m/a g2 a2 a2 d2 d2

}
